# prometheus.yml
global:
  scrape_interval: 15s # Default scrape interval
  evaluation_interval: 15s # Default evaluation interval

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071'] # Target the JMX exporter port on the Kafka service
    scrape_interval: 10s  # More frequent scraping for metrics
    scrape_timeout: 5s    # Prevent long hangs
  - job_name: 'producer' # Add this job for the producer
    static_configs:
      - targets: ['producer:8080'] # Target the producer's actuator endpoint (internal port)
    scrape_interval: 10s
    scrape_timeout: 5s
  - job_name: 'consumer' # Uncomment and ensure this job targets the consumer
    static_configs:
      - targets: ['consumer:8080'] # Target the consumer's actuator endpoint (internal port)
    scrape_interval: 10s
    scrape_timeout: 5s